### ISSUE TITLE
Good job on preventing SQL Injections!

### ISSUE THREAD

**Issue by tamerNasser** [facn6/6-sam-ameer-books#27]
https://github.com/facn6/6-sam-ameer-books/blob/d0a307bd4a05c9143097047e637df063e0ac3198/src/queries/addBook.js#L27-L28

**Comment by samjam48** [comment]
ahh that's why we do this. I will be honest and say I was copying conventions from Shireen's DB workshops and hadn't found time to ask about it.

So If I just do a normal `SQL statement STUFF ${variable}` then that allows the code injection?
But why does having the variable placed into it from the method we've used prevent that when we aren't performing any further validation on it..?
